name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet New Contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hello! Thank you for opening your first issue on our repository. We appreciate your contribution and look forward to your feedback!"
          pr-message: "🎉 Welcome! We're excited to see your first pull request. Thank you for your contribution!"
